### ISSUE TITLE
To Update Deadline Of Project

### ISSUE THREAD

**Issue by JustHarxsh** [Amplication-Octernships/Amplication-Plugin-Task#10]
The Deadline of the project is showing 26June Kindly Update that 
Thank You :) @mulygottlieb @ashwinexe

**Comment by ashwinexe** [comment]
Raised a [PR](https://github.com/Amplication-Octernships/Amplication-Plugin-Task/pull/11) to fix this

For everyone's context, Amplication has extended deadline by a week 
<img width="375" alt="image" src="https://github.com/Amplication-Octernships/Amplication-Plugin-Task/assets/53075480/2a6362ff-c7b4-413a-ad6e-33f41d848616">

**Comment by abhinav-0401** [comment]
@ashwinexe Does this mean we can complete the task by 5th July?

**Comment by ashwinexe** [comment]
> @ashwinexe Does this mean we can complete the task by 5th July?

Yes
